//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABWen
{
    using System;
    using System.Collections.Generic;
    
    public partial class opilane
    {
        public int opilaneId { get; set; }
        public string eesnimi { get; set; }
        public string perenimi { get; set; }
        public System.TimeSpan syniaeg { get; set; }
    
        public virtual ryhm ryhm { get; set; }
    }
}
