//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ABWen
{
    using System;
    using System.Collections.Generic;
    
    public partial class ryhm
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public ryhm()
        {
            this.opilane = new HashSet<opilane>();
        }
    
        public int ryhmId { get; set; }
        public string ryhmNimi { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<opilane> opilane { get; set; }
        public virtual Osakond0 Osakond0 { get; set; }
    }
}
